In [1]:
import pandas as pd
from sqlalchemy import create_engine
import pymysql

from twitpol import config, db

In [2]:
pd.set_option('display.max_columns', 999)

In [3]:
host = 'database-2.czpegg91dqsv.us-east-2.rds.amazonaws.com'
port = 3306
user = 'admin'
password = 'dbpass111'
charset = 'utf8'
database = 'test_2'

db_str = f'mysql+pymysql://{user}:{password}@{host}:{port}/'
engine = create_engine(db_str)
engine.connect().execute(f"CREATE DATABASE IF NOT EXISTS {database};")
db_str_new = db_str + database
engine_new = create_engine(db_str_new)

/home/ubuntu/miniconda3/envs/twitpol-env/lib/python3.7/site-packages/pymysql/cursors.py:170: Warning: (1007, "Can't create database 'test_2'; database exists")
  result = self._query(query)

In [4]:
engine = db.get_db_engine(create_database=False)

In [5]:
pd.read_sql('SELECT COUNT(*) FROM tweets;', con=engine)

   COUNT(*)
0   1926767

In [21]:
test = pd.read_sql('SELECT * FROM tweets LIMIT 50;', con=engine)
test.head()

,index,id,conversation_id,created_at,date,timezone,place,tweet,hashtags,cashtags,user_id,user_id_str,username,name,day,hour,link,retweet,nlikes,nreplies,nretweets,quote_url,search,near,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date
0,0,1102357988264669184,1102353254069891073,1551657599000,2019-03-03 23:59:59,UTC,,before anyone else tries to comment about bern...,[],[],787208453362036736,787208453362036736,pronouncedzara,SANDERS,6,23,https://twitter.com/pronouncedzara/status/1102...,0,219,14,22,,"Bernie Sanders OR ""Bernie"" OR ""Sanders"" OR ""#F...",,,,,,,"[{'user_id': '787208453362036736', 'username':...",
1,1,1102357982329823232,1102345807649558528,1551657598000,2019-03-03 23:59:58,UTC,,American citizens Bern!,[],[],1089193640541343745,1089193640541343745,katrooch1,SANDERS,6,23,https://twitter.com/katrooch1/status/110235798...,0,0,0,0,,"Bernie Sanders OR ""Bernie"" OR ""Sanders"" OR ""#F...",,,,,,,"[{'user_id': '1089193640541343745', 'username'...",
2,2,1102357980681388032,1102312496617074689,1551657598000,2019-03-03 23:59:58,UTC,,"Who was and who is Bernie, anyone knows. ?",[],[],830914308921896961,830914308921896961,Reinie214,SANDERS,6,23,https://twitter.com/Reinie214/status/110235798...,0,0,0,0,,"Bernie Sanders OR ""Bernie"" OR ""Sanders"" OR ""#F...",,,,,,,"[{'user_id': '830914308921896961', 'username':...",
3,3,1102357975090585600,1102357975090585600,1551657596000,2019-03-03 23:59:56,UTC,,COMMENTARY: Unless you are one of the few who ...,[],[],17041374,17041374,wgbhnews,SANDERS,6,22,https://twitter.com/wgbhnews/status/1102357975...,0,7,1,6,,"Bernie Sanders OR ""Bernie"" OR ""Sanders"" OR ""#F...",,,,,,,"[{'user_id': '17041374', 'username': 'wgbhnews...",
4,4,1102357971550507008,1102348709373849600,1551657595000,2019-03-03 23:59:55,UTC,,We donât have to argue about @SenSanders . Jus...,[],[],4703492125,4703492125,tenspeed1776,SANDERS,6,22,https://twitter.com/tenspeed1776/status/110235...,0,7,1,1,,"Bernie Sanders OR ""Bernie"" OR ""Sanders"" OR ""#F...",,,,,,,"[{'user_id': '4703492125', 'username': 'tenspe...",

In [17]:
test['date']

0     2019-03-03 23:59:59
1     2019-03-03 23:59:58
2     2019-03-03 23:59:58
3     2019-03-03 23:59:56
4     2019-03-03 23:59:55
5     2019-03-03 23:59:54
6     2019-03-03 23:59:53
7     2019-03-03 23:59:52
8     2019-03-03 23:59:51
9     2019-03-03 23:59:50
10    2019-03-03 23:59:50
11    2019-03-03 23:59:48
12    2019-03-03 23:59:47
13    2019-03-03 23:59:46
14    2019-03-03 23:59:43
15    2019-03-03 23:59:41
16    2019-03-03 23:59:40
17    2019-03-03 23:59:39
18    2019-03-03 23:59:38
19    2019-03-03 23:59:37
20    2019-03-03 23:59:36
21    2019-03-03 23:59:35
22    2019-03-03 23:59:34
23    2019-03-03 23:59:32
24    2019-03-03 23:59:32
25    2019-03-03 23:59:31
26    2019-03-03 23:59:30
27    2019-03-03 23:59:29
28    2019-03-03 23:59:29
29    2019-03-03 23:59:29
30    2019-03-03 23:59:28
31    2019-03-03 23:59:26
32    2019-03-03 23:59:24
33    2019-03-03 23:59:24
34    2019-03-03 23:59:24
35    2019-03-03 23:59:23
36    2019-03-03 23:59:21
37    2019-03-03 23:59:19
38    2019-03-03 23:59:19
39    2019-03-03 23:59:18
40    2019-03-03 23:59:17
41    2019-03-03 23:59:16
42    2019-03-03 23:59:14
43    2019-03-03 23:59:13
44    2019-03-03 23:59:12
45    2019-03-03 23:59:09
46    2019-03-03 23:59:08
47    2019-03-03 23:59:08
48    2019-03-03 23:59:07
49    2019-03-03 23:59:05
Name: date, dtype: object

In [18]:
# select specific day
day = '2019-03-03'
tweets_per_day = test.loc[test['date'][:10] == day]

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

In [27]:
test['date'][:][:10]

0    2019-03-03 23:59:59
1    2019-03-03 23:59:58
2    2019-03-03 23:59:58
3    2019-03-03 23:59:56
4    2019-03-03 23:59:55
5    2019-03-03 23:59:54
6    2019-03-03 23:59:53
7    2019-03-03 23:59:52
8    2019-03-03 23:59:51
9    2019-03-03 23:59:50
Name: date, dtype: object