In [2]:
import pandas as pd
from sqlalchemy import create_engine
import pymysql

from twitpol import config, db

In [6]:
pd.set_option('display.max_columns', 999)

In [8]:
host = 'database-2.czpegg91dqsv.us-east-2.rds.amazonaws.com'
port = 3306
user = 'admin'
password = 'dbpass111'
charset = 'utf8'
database = 'test_2'

db_str = f'mysql+pymysql://{user}:{password}@{host}:{port}/'
engine = create_engine(db_str)
engine.connect().execute(f"CREATE DATABASE IF NOT EXISTS {database};")
db_str_new = db_str + database
engine_new = create_engine(db_str_new)

/home/ubuntu/miniconda3/envs/twitpol-env/lib/python3.7/site-packages/pymysql/cursors.py:170: Warning: (1007, "Can't create database 'test_2'; database exists")
  result = self._query(query)

In [9]:
df = pd.DataFrame({
    'name': ['A', 'B', 'C', 'D'],
    'age': [12, 13, 14, 15]
})
df

  name  age
0    A   12
1    B   13
2    C   14
3    D   15

In [11]:
df.to_sql('test_table', con=engine_new, if_exists='append')

In [15]:
pd.read_sql('SELECT * FROM test_table;', con=engine_new, index_col='index')

      name  age
index
0        A   12
1        B   13
2        C   14
3        D   15

In [4]:
engine = db.get_db_engine(create_database=False)

In [7]:
pd.read_sql(f'SELECT * FROM tweets_db LIMIT 100;', con=engine)

,index,id,conversation_id,created_at,date,timezone,place,tweet,hashtags,cashtags,user_id,user_id_str,username,name,day,hour,link,retweet,nlikes,nreplies,nretweets,quote_url,search,near,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date
0,0,1080252272637038597,1080244340839116810,1546387186000,2019-01-01 23:59:46,UTC,,Joe or Amy,[],[],881176727426179072,881176727426179072,NanJanChr195877,BIDEN,4,20,https://twitter.com/NanJanChr195877/status/108...,0,0,0,0,,"Joe Biden OR ""Joseph Biden"" OR ""Biden"" OR ""Dia...",,,,,,,"[{'user_id': '881176727426179072', 'username':...",
1,1,1080252220204027904,1080189345259315209,1546387174000,2019-01-01 23:59:34,UTC,"Bronx, NY","Black people, please donâ€™t trust Joe Biden, he...",[],[],82147388,82147388,bogart7777,BIDEN,4,16,https://twitter.com/bogart7777/status/10802522...,0,1,0,0,,"Joe Biden OR ""Joseph Biden"" OR ""Biden"" OR ""Dia...",,,,,,,"[{'user_id': '82147388', 'username': 'bogart77...",
2,2,1080252076658180096,1080189345259315209,1546387139000,2019-01-01 23:58:59,UTC,,What % of @nytimes profits is driven by spendi...,[],[],29346712,29346712,techiedad,BIDEN,4,07,https://twitter.com/techiedad/status/108025207...,0,29,0,4,,"Joe Biden OR ""Joseph Biden"" OR ""Biden"" OR ""Dia...",,,,,,,"[{'user_id': '29346712', 'username': 'techieda...",
3,3,1080251922286813187,1079871719861600257,1546387103000,2019-01-01 23:58:23,UTC,,So what you're saying is Joe Biden is a Republ...,[],[],67548940,67548940,LeftOfStalin,BIDEN,3,21,https://twitter.com/LeftOfStalin/status/108025...,0,2,0,0,,"Joe Biden OR ""Joseph Biden"" OR ""Biden"" OR ""Dia...",,,,,,,"[{'user_id': '67548940', 'username': 'LeftOfSt...",
4,4,1080251916678967296,1080248896444612610,1546387101000,2019-01-01 23:58:21,UTC,,Louis CK lives in your town? Iâ€™m sorry. You ...,[],[],308753213,308753213,phillycheryl,BIDEN,3,20,https://twitter.com/phillycheryl/status/108025...,0,0,1,0,,"Joe Biden OR ""Joseph Biden"" OR ""Biden"" OR ""Dia...",,,,,,,"[{'user_id': '308753213', 'username': 'phillyc...",
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,1080239978100203521,1080235018310635521,1546384255000,2019-01-01 23:10:55,UTC,,"And really, who exactly is going to stand agai...",[],[],1008384135575023616,1008384135575023616,JayHSalem,BIDEN,5,21,https://twitter.com/JayHSalem/status/108023997...,0,2,1,2,,"Joe Biden OR ""Joseph Biden"" OR ""Biden"" OR ""Dia...",,,,,,,"[{'user_id': '1008384135575023616', 'username'...",
96,96,1080239524913934337,1080235676254289921,1546384147000,2019-01-01 23:09:07,UTC,,Joe Biden,[],[],119956464,119956464,Genuflectional,BIDEN,4,15,https://twitter.com/Genuflectional/status/1080...,0,1,0,0,,"Joe Biden OR ""Joseph Biden"" OR ""Biden"" OR ""Dia...",,,,,,,"[{'user_id': '119956464', 'username': 'Genufle...",
97,97,1080239223699955713,1080239223699955713,1546384075000,2019-01-01 23:07:55,UTC,,All we have to do to stop Joe Biden's presiden...,[],[],912100634,912100634,AlanSoAngry,BIDEN,3,19,https://twitter.com/AlanSoAngry/status/1080239...,0,0,0,1,,"Joe Biden OR ""Joseph Biden"" OR ""Biden"" OR ""Dia...",,,,,,,"[{'user_id': '912100634', 'username': 'AlanSoA...",
98,98,1080238649789173760,1079871719861600257,1546383938000,2019-01-01 23:05:38,UTC,,My 62 year old dad won't vote if it's Joe Bide...,[],[],928824279587680256,928824279587680256,SeanDaHam,BIDEN,2,05,https://twitter.com/SeanDaHam/status/108023864...,0,0,0,0,,"Joe Biden OR ""Joseph Biden"" OR ""Biden"" OR ""Dia...",,,,,,,"[{'user_id': '928824279587680256', 'username':...",
99,99,1080238589575860224,1080238589575860224,1546383924000,2019-01-01 23:05:24,UTC,,If you point out Joe Biden is no different tha...,[],[],1549319011,1549319011,pacifistHULK,BIDEN,2,02,https://twitter.com/pacifistHULK/status/108023...,0,3,1,0,,"Joe Biden OR ""Joseph Biden"" OR ""Biden"" OR ""Dia...",,,,,,,"[{'user_id': '1549319011', 'username': 'pacifi...",

In [10]:
pd.read_sql('SELECT COUNT(*) FROM tweets_db;', con=engine)

ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'tweets_db.tweets_db' doesn't exist")
[SQL: SELECT COUNT(*) FROM tweets_db;]
(Background on this error at: http://sqlalche.me/e/f405)

In [9]:
engine.execute('DROP TABLE IF EXISTS tweets_db')