In [1]:
import pandas as pd
from sqlalchemy import create_engine
import pymysql

from twitpol import config, db

In [2]:
pd.set_option('display.max_columns', 999)

In [8]:
host = 'database-2.czpegg91dqsv.us-east-2.rds.amazonaws.com'
port = 3306
user = 'admin'
password = 'dbpass111'
charset = 'utf8'
database = 'test_2'

db_str = f'mysql+pymysql://{user}:{password}@{host}:{port}/'
engine = create_engine(db_str)
engine.connect().execute(f"CREATE DATABASE IF NOT EXISTS {database};")
db_str_new = db_str + database
engine_new = create_engine(db_str_new)

/home/ubuntu/miniconda3/envs/twitpol-env/lib/python3.7/site-packages/pymysql/cursors.py:170: Warning: (1007, "Can't create database 'test_2'; database exists")
  result = self._query(query)

In [9]:
df = pd.DataFrame({
    'name': ['A', 'B', 'C', 'D'],
    'age': [12, 13, 14, 15]
})
df

  name  age
0    A   12
1    B   13
2    C   14
3    D   15

In [11]:
df.to_sql('test_table', con=engine_new, if_exists='append')

In [15]:
pd.read_sql('SELECT * FROM test_table;', con=engine_new, index_col='index')

      name  age
index
0        A   12
1        B   13
2        C   14
3        D   15

In [3]:
engine = db.get_db_engine(create_database=False)

In [ ]:
pd.read_sql(f'SELECT * FROM tweets WHERE name = "WARREN";', con=engine)

In [7]:
pd.read_sql('SELECT COUNT(*) FROM tweets;', con=engine)

   COUNT(*)
0     99124

In [16]:
pd.read_sql('SELECT * FROM tweets;', con=engine).tail(10)

,index,id,conversation_id,created_at,date,timezone,place,tweet,hashtags,cashtags,user_id,user_id_str,username,name,day,hour,link,retweet,nlikes,nreplies,nretweets,quote_url,search,near,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date
99114,3709,1112835208804556801,1112835208804556801,1554155563000,2019-04-01 21:52:43,UTC,,Joy Behar Defends Creepy Joe Biden: 'He Touche...,['#aag'],[],1494835716,1494835716,AIIAmericanGirI,BIDEN,1,14,https://twitter.com/AIIAmericanGirI/status/111...,0,2,1,1,,"Joe Biden OR ""Joseph Biden"" OR ""Biden"" OR ""Dia...",,,,,,,"[{'user_id': '1494835716', 'username': 'AIIAme...",
99115,3710,1112835201577766912,1112835201577766912,1554155562000,2019-04-01 21:52:42,UTC,,Impeached President Bill Clinton's crime boss ...,"['#berniesanders', '#joebiden', '#joebidensnif...",[],174873047,174873047,will_the_thrilI,BIDEN,1,14,https://twitter.com/will_the_thrilI/status/111...,0,0,0,0,,"Joe Biden OR ""Joseph Biden"" OR ""Biden"" OR ""Dia...",,,,,,,"[{'user_id': '174873047', 'username': 'will_th...",
99116,3711,1112835184724860928,1112835184724860928,1554155558000,2019-04-01 21:52:38,UTC,,Connecticut woman says then-Vice President Joe...,[],[],708199243,708199243,NCManoukian,BIDEN,1,13,https://twitter.com/NCManoukian/status/1112835...,0,0,0,0,,"Joe Biden OR ""Joseph Biden"" OR ""Biden"" OR ""Dia...",,,,,,,"[{'user_id': '708199243', 'username': 'NCManou...",
99117,3712,1112835160842620931,1112835160842620931,1554155552000,2019-04-01 21:52:32,UTC,,I have to say watching the socialist attack a ...,"['#moron', '#liar', '#mutt', '#trumptrain2020'...",[],24635878,24635878,shocker23456,BIDEN,1,11,https://twitter.com/shocker23456/status/111283...,0,1,0,3,,"Joe Biden OR ""Joseph Biden"" OR ""Biden"" OR ""Dia...",,,,,,,"[{'user_id': '24635878', 'username': 'shocker2...",
99118,3713,1112835146162626561,1112835146162626561,1554155548000,2019-04-01 21:52:28,UTC,,'Gropey Uncle' Joe Biden has always been creep...,[],[],736095344,736095344,WTPatty,BIDEN,1,10,https://twitter.com/WTPatty/status/11128351461...,0,2,0,0,,"Joe Biden OR ""Joseph Biden"" OR ""Biden"" OR ""Dia...",,,,,,,"[{'user_id': '736095344', 'username': 'WTPatty...",
99119,3714,1112835145806036992,1112833731713130498,1554155548000,2019-04-01 21:52:28,UTC,,I dare to think of everything Joe Biden may ha...,['#sniffed'],[],3301554829,3301554829,thiviergemike,BIDEN,1,10,https://twitter.com/thiviergemike/status/11128...,0,1,0,0,,"Joe Biden OR ""Joseph Biden"" OR ""Biden"" OR ""Dia...",,,,,,,"[{'user_id': '3301554829', 'username': 'thivie...",
99120,3715,1112835144350658560,1112835144350658560,1554155548000,2019-04-01 21:52:28,UTC,,An Awkward Kiss Changed How I Saw Joe Biden h...,[],[],102135961,102135961,JesseConover,BIDEN,1,10,https://twitter.com/JesseConover/status/111283...,0,0,0,0,,"Joe Biden OR ""Joseph Biden"" OR ""Biden"" OR ""Dia...",,,,,,,"[{'user_id': '102135961', 'username': 'JesseCo...",
99121,3716,1112835124406566912,1112791380768616449,1554155543000,2019-04-01 21:52:23,UTC,,Creepy Joe Biden.,[],[],79768881,79768881,Hypidiomorphic,BIDEN,1,09,https://twitter.com/Hypidiomorphic/status/1112...,0,0,0,0,,"Joe Biden OR ""Joseph Biden"" OR ""Biden"" OR ""Dia...",,,,,,,"[{'user_id': '79768881', 'username': 'Hypidiom...",
99122,3717,1112835079603191808,1112835079603191808,1554155533000,2019-04-01 21:52:13,UTC,,I am not a huge fan of Joe Biden and wouldn’t ...,[],[],3158646817,3158646817,rhiggins00,BIDEN,1,06,https://twitter.com/rhiggins00/status/11128350...,0,0,0,0,https://twitter.com/AutohistorianUS/status/111...,"Joe Biden OR ""Joseph Biden"" OR ""Biden"" OR ""Dia...",,,,,,,"[{'user_id': '3158646817', 'username': 'rhiggi...",
99123,3718,1112835064541429766,1112793964447449088,1554155529000,2019-04-01 21:52:09,UTC,,Creepy Uncle Joe Boner Biden ...his days of th...,[],[],45982350,45982350,lightchaser17,BIDEN,1,05,https://twitter.com/lightchaser17/status/11128...,0,1,0,0,,"Joe Biden OR ""Joseph Biden"" OR ""Biden"" OR ""Dia...",,,,,,,"[{'user_id': '45982350', 'username': 'lightcha...",