In [6]:
from datetime import datetime as dt
from datetime import timedelta

import pandas as pd

from twitpol import config, utils

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [7]:
pd.set_option('display.max_columns', 999)

In [7]:
pd.read_csv('../data/twint_test.csv')

,id,conversation_id,created_at,date,time,timezone,user_id,username,name,place,tweet,mentions,urls,photos,replies_count,retweets_count,likes_count,hashtags,cashtags,link,retweet,quote_url,video,near,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date
0,1123074487237234690,1123063323463962625,1556596798000,2019-04-29,23:59:58,EST,26056578,soqrbrad,soqrbrad,NaN,So releasing millions of Americans’ drivers li...,"['ninaturner', 'berniesanders']",[],[],1,0,1,[],[],https://twitter.com/soqrbrad/status/1123074487...,False,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '26056578', 'username': 'soqrbrad...",NaN
1,1123074459135619072,1123072670654799872,1556596791000,2019-04-29,23:59:51,EST,377778958,kimdallas07,🌎Kimberly🦄,NaN,Uh no. \n\n@ninaturner is our fearless leader!...,"['pmoallemian', 'nofascistlies', 'berniesander...",[],[],1,1,0,[],[],https://twitter.com/kimdallas07/status/1123074...,False,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '377778958', 'username': 'kimdall...",NaN
2,1123074431197147136,1123074431197147136,1556596784000,2019-04-29,23:59:44,EST,1076724302735527936,randypcox2,randypcox,NaN,The Parallel Campaigns Of Joe Biden And Bernie...,[],['https://www.huffpost.com/entry/the-parallel-...,[],0,0,0,[],[],https://twitter.com/randypcox2/status/11230744...,False,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '1076724302735527936', 'username'...",NaN
3,1123074422246649856,1123074422246649856,1556596782000,2019-04-29,23:59:42,EST,2761592377,a35362,April Spivey,NaN,The Bernie Sanders Army Gears Up For The Next ...,['thedailybeast'],['https://www.thedailybeast.com/the-bernie-san...,[],0,0,0,[],[],https://twitter.com/a35362/status/112307442224...,False,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '2761592377', 'username': 'a35362...",NaN
4,1123074348867313665,1123074348867313665,1556596765000,2019-04-29,23:59:25,EST,803966646,15minutenews,15 Minute News,NaN,Bernie Sanders draws sharp contrasts between h...,[],['https://www.15minutenews.com/article/1642550...,[],0,0,0,['#news'],[],https://twitter.com/15MinuteNews/status/112307...,False,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '803966646', 'username': '15Minut...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,1123069623803498496,1122570639733329920,1556595638000,2019-04-29,23:40:38,EST,221969660,simmerbaggins,Vickie Brown,NaN,"Bernie, your statement is the height of cognit...",['berniesanders'],[],[],0,0,0,[],[],https://twitter.com/SimmerBaggins/status/11230...,False,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '221969660', 'username': 'SimmerB...",NaN
336,1123069619529572352,1122950661665120261,1556595637000,2019-04-29,23:40:37,EST,1955692782,jaiw69,Jai 🦋 Vote Blue 2020 ✝️ 🙏🏼♥️,NaN,"Outspoken Marc, u r exactly right about the be...","['marcandersonnwo', 'tdickinson511', 'berniesa...",[],[],0,0,1,[],[],https://twitter.com/JaiW69/status/112306961952...,False,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '1955692782', 'username': 'JaiW69...",NaN
337,1123069608091500544,1122565592106643456,1556595634000,2019-04-29,23:40:34,EST,1021914462041694208,catchypython0,SpookyPython,NaN,You rock! Please keep doing art like this when...,"['feelin_thebern', 'people4bernie', 'berniesan...",[],[],0,0,1,[],[],https://twitter.com/CatchyPython0/status/11230...,False,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '1021914462041694208', 'username'...",NaN
338,1123069606346682368,1123069606346682368,1556595634000,2019-04-29,23:40:34,EST,1400026964,thecyanpost,TheCyanPost,NaN,The Parallel Campaigns Of Joe Biden And Bernie...,[],['https://www.huffpost.com/entry/the-parallel-...,['https://pbs.twimg.com/media/D5Xx2vGUcAAH5fJ....,0,2,0,[],[],https://twitter.com/TheCyanPost/status/1123069...,False,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '1400026964', 'username': 'TheCya...",NaN
339,1123069606061416449,1123069606061416449,1556595634000,2019-04-29,23:40:34,EST,476993726,srm1n,Şermin Kızık,NaN,@null Bernie Sanders draws sharp contrasts bet...,['null'],['https://www.cnn.com/2019/04/29/politics/bern...,[],0,0,0,[],[],https://twitter.com/Srm1n/status/1123069606061...,False,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,"[{'user_id': '476993726', 'username': 'Srm1n'}...",NaN

In [8]:
d1_str = '2019-01-01'
d2_str = '2019-11-04'
step = 1

In [9]:
dategen = utils.date_range(d1_str, d2_str, step=1)

In [10]:
for d1, d2 in dategen:
    print(d1, d2)

2019-01-01 2019-01-02
2019-01-02 2019-01-03
2019-01-03 2019-01-04
2019-01-04 2019-01-05
2019-01-05 2019-01-06
2019-01-06 2019-01-07
2019-01-07 2019-01-08
2019-01-08 2019-01-09
2019-01-09 2019-01-10
2019-01-10 2019-01-11
2019-01-11 2019-01-12
2019-01-12 2019-01-13
2019-01-13 2019-01-14
2019-01-14 2019-01-15
2019-01-15 2019-01-16
2019-01-16 2019-01-17
2019-01-17 2019-01-18
2019-01-18 2019-01-19
2019-01-19 2019-01-20
2019-01-20 2019-01-21
2019-01-21 2019-01-22
2019-01-22 2019-01-23
2019-01-23 2019-01-24
2019-01-24 2019-01-25
2019-01-25 2019-01-26
2019-01-26 2019-01-27
2019-01-27 2019-01-28
2019-01-28 2019-01-29
2019-01-29 2019-01-30
2019-01-30 2019-01-31
2019-01-31 2019-02-01
2019-02-01 2019-02-02
2019-02-02 2019-02-03
2019-02-03 2019-02-04
2019-02-04 2019-02-05
2019-02-05 2019-02-06
2019-02-06 2019-02-07
2019-02-07 2019-02-08
2019-02-08 2019-02-09
2019-02-09 2019-02-10
2019-02-10 2019-02-11
2019-02-11 2019-02-12
2019-02-12 2019-02-13
2019-02-13 2019-02-14
2019-02-14 2019-02-15
2019-02-15 2019-02-16
2019-02-16 2019-02-17
2019-02-17 2019-02-18
2019-02-18 2019-02-19
2019-02-19 2019-02-20
2019-02-20 2019-02-21
2019-02-21 2019-02-22
2019-02-22 2019-02-23
2019-02-23 2019-02-24
2019-02-24 2019-02-25
2019-02-25 2019-02-26
2019-02-26 2019-02-27
2019-02-27 2019-02-28
2019-02-28 2019-03-01
2019-03-01 2019-03-02
2019-03-02 2019-03-03
2019-03-03 2019-03-04
2019-03-04 2019-03-05
2019-03-05 2019-03-06
2019-03-06 2019-03-07
2019-03-07 2019-03-08
2019-03-08 2019-03-09
2019-03-09 2019-03-10
2019-03-10 2019-03-11
2019-03-11 2019-03-12
2019-03-12 2019-03-13
2019-03-13 2019-03-14
2019-03-14 2019-03-15
2019-03-15 2019-03-16
2019-03-16 2019-03-17
2019-03-17 2019-03-18
2019-03-18 2019-03-19
2019-03-19 2019-03-20
2019-03-20 2019-03-21
2019-03-21 2019-03-22
2019-03-22 2019-03-23
2019-03-23 2019-03-24
2019-03-24 2019-03-25
2019-03-25 2019-03-26
2019-03-26 2019-03-27
2019-03-27 2019-03-28
2019-03-28 2019-03-29
2019-03-29 2019-03-30
2019-03-30 2019-03-31
2019-03-31 2019-04-01
2019-04-01 2019-04-02
2019-04-02 2019-04-03
2019-04-03 2019-04-04
2019-04-04 2019-04-05
2019-04-05 2019-04-06
2019-04-06 2019-04-07
2019-04-07 2019-04-08
2019-04-08 2019-04-09
2019-04-09 2019-04-10
2019-04-10 2019-04-11
2019-04-11 2019-04-12
2019-04-12 2019-04-13
2019-04-13 2019-04-14
2019-04-14 2019-04-15
2019-04-15 2019-04-16
2019-04-16 2019-04-17
2019-04-17 2019-04-18
2019-04-18 2019-04-19
2019-04-19 2019-04-20
2019-04-20 2019-04-21
2019-04-21 2019-04-22
2019-04-22 2019-04-23
2019-04-23 2019-04-24
2019-04-24 2019-04-25
2019-04-25 2019-04-26
2019-04-26 2019-04-27
2019-04-27 2019-04-28
2019-04-28 2019-04-29
2019-04-29 2019-04-30
2019-04-30 2019-05-01
2019-05-01 2019-05-02
2019-05-02 2019-05-03
2019-05-03 2019-05-04
2019-05-04 2019-05-05
2019-05-05 2019-05-06
2019-05-06 2019-05-07
2019-05-07 2019-05-08
2019-05-08 2019-05-09
2019-05-09 2019-05-10
2019-05-10 2019-05-11
2019-05-11 2019-05-12
2019-05-12 2019-05-13
2019-05-13 2019-05-14
2019-05-14 2019-05-15
2019-05-15 2019-05-16
2019-05-16 2019-05-17
2019-05-17 2019-05-18
2019-05-18 2019-05-19
2019-05-19 2019-05-20
2019-05-20 2019-05-21
2019-05-21 2019-05-22
2019-05-22 2019-05-23
2019-05-23 2019-05-24
2019-05-24 2019-05-25
2019-05-25 2019-05-26
2019-05-26 2019-05-27
2019-05-27 2019-05-28
2019-05-28 2019-05-29
2019-05-29 2019-05-30
2019-05-30 2019-05-31
2019-05-31 2019-06-01
2019-06-01 2019-06-02
2019-06-02 2019-06-03
2019-06-03 2019-06-04
2019-06-04 2019-06-05
2019-06-05 2019-06-06
2019-06-06 2019-06-07
2019-06-07 2019-06-08
2019-06-08 2019-06-09
2019-06-09 2019-06-10
2019-06-10 2019-06-11
2019-06-11 2019-06-12
2019-06-12 2019-06-13
2019-06-13 2019-06-14
2019-06-14 2019-06-15
2019-06-15 2019-06-16
2019-06-16 2019-06-17
2019-06-17 2019-06-18
2019-06-18 2019-06-19
2019-06-19 2019-06-20
2019-06-20 2019-06-21
2019-06-21 2019-06-22
2019-06-22 2019-06-23
2019-06-23 2019-06-24
2019-06-24 2019-06-25
2019-06-25 2019-06-26
2019-06-26 2019-06-27
2019-06-27 2019-06-28
2019-06-28 2019-06-29
2019-06-29 2019-06-30
2019-06-30 2019-07-01
2019-07-01 2019-07-02
2019-07-02 2019-07-03
2019-07-03 2019-07-04
2019-07-04 2019-07-05
2019-07-05 2019-07-06
2019-07-06 2019-07-07
2019-07-07 2019-07-08
2019-07-08 2019-07-09
2019-07-09 2019-07-10
2019-07-10 2019-07-11
2019-07-11 2019-07-12
2019-07-12 2019-07-13
2019-07-13 2019-07-14
2019-07-14 2019-07-15
2019-07-15 2019-07-16
2019-07-16 2019-07-17
2019-07-17 2019-07-18
2019-07-18 2019-07-19
2019-07-19 2019-07-20
2019-07-20 2019-07-21
2019-07-21 2019-07-22
2019-07-22 2019-07-23
2019-07-23 2019-07-24
2019-07-24 2019-07-25
2019-07-25 2019-07-26
2019-07-26 2019-07-27
2019-07-27 2019-07-28
2019-07-28 2019-07-29
2019-07-29 2019-07-30
2019-07-30 2019-07-31
2019-07-31 2019-08-01
2019-08-01 2019-08-02
2019-08-02 2019-08-03
2019-08-03 2019-08-04
2019-08-04 2019-08-05
2019-08-05 2019-08-06
2019-08-06 2019-08-07
2019-08-07 2019-08-08
2019-08-08 2019-08-09
2019-08-09 2019-08-10
2019-08-10 2019-08-11
2019-08-11 2019-08-12
2019-08-12 2019-08-13
2019-08-13 2019-08-14
2019-08-14 2019-08-15
2019-08-15 2019-08-16
2019-08-16 2019-08-17
2019-08-17 2019-08-18
2019-08-18 2019-08-19
2019-08-19 2019-08-20
2019-08-20 2019-08-21
2019-08-21 2019-08-22
2019-08-22 2019-08-23
2019-08-23 2019-08-24
2019-08-24 2019-08-25
2019-08-25 2019-08-26
2019-08-26 2019-08-27
2019-08-27 2019-08-28
2019-08-28 2019-08-29
2019-08-29 2019-08-30
2019-08-30 2019-08-31
2019-08-31 2019-09-01
2019-09-01 2019-09-02
2019-09-02 2019-09-03
2019-09-03 2019-09-04
2019-09-04 2019-09-05
2019-09-05 2019-09-06
2019-09-06 2019-09-07
2019-09-07 2019-09-08
2019-09-08 2019-09-09
2019-09-09 2019-09-10
2019-09-10 2019-09-11
2019-09-11 2019-09-12
2019-09-12 2019-09-13
2019-09-13 2019-09-14
2019-09-14 2019-09-15
2019-09-15 2019-09-16
2019-09-16 2019-09-17
2019-09-17 2019-09-18
2019-09-18 2019-09-19
2019-09-19 2019-09-20
2019-09-20 2019-09-21
2019-09-21 2019-09-22
2019-09-22 2019-09-23
2019-09-23 2019-09-24
2019-09-24 2019-09-25
2019-09-25 2019-09-26
2019-09-26 2019-09-27
2019-09-27 2019-09-28
2019-09-28 2019-09-29
2019-09-29 2019-09-30
2019-09-30 2019-10-01
2019-10-01 2019-10-02
2019-10-02 2019-10-03
2019-10-03 2019-10-04
2019-10-04 2019-10-05
2019-10-05 2019-10-06
2019-10-06 2019-10-07
2019-10-07 2019-10-08
2019-10-08 2019-10-09
2019-10-09 2019-10-10
2019-10-10 2019-10-11
2019-10-11 2019-10-12
2019-10-12 2019-10-13
2019-10-13 2019-10-14
2019-10-14 2019-10-15
2019-10-15 2019-10-16
2019-10-16 2019-10-17
2019-10-17 2019-10-18
2019-10-18 2019-10-19
2019-10-19 2019-10-20
2019-10-20 2019-10-21
2019-10-21 2019-10-22
2019-10-22 2019-10-23
2019-10-23 2019-10-24
2019-10-24 2019-10-25
2019-10-25 2019-10-26
2019-10-26 2019-10-27
2019-10-27 2019-10-28
2019-10-28 2019-10-29
2019-10-29 2019-10-30
2019-10-30 2019-10-31
2019-10-31 2019-11-01
2019-11-01 2019-11-02
2019-11-02 2019-11-03
2019-11-03 2019-11-04

In [11]:

step = timedelta(days=1)
fmt_str = '%Y-%m-%d'

d1 = dt.strptime(d1_str, fmt_str)
d2 = dt.strptime(d2_str, fmt_str)

In [12]:
d1

datetime.datetime(2019, 1, 1, 0, 0)

In [13]:
d2

datetime.datetime(2019, 11, 4, 0, 0)

In [14]:
(d2 - d1).days

307

In [15]:
step

datetime.timedelta(days=1)

In [16]:
curr_date = d1 + step

In [17]:
curr_date

datetime.datetime(2019, 1, 2, 0, 0)

In [18]:
curr_date <= d2

True

In [19]:
int(curr_date)

TypeError: int() argument must be a string, a bytes-like object or a number, not 'datetime.datetime'

In [20]:
i = 0
curr_date = d1
while curr_date <= d2:
    if i % 50 == 0:
        print(curr_date)
    curr_date += step
    i += 1

2019-01-01 00:00:00
2019-02-20 00:00:00
2019-04-11 00:00:00
2019-05-31 00:00:00
2019-07-20 00:00:00
2019-09-08 00:00:00
2019-10-28 00:00:00

In [25]:
dt.today().date()

datetime.date(2019, 11, 9)